---
workspace:
  base: /go
  path: src/github.com/Abdul2/awsdetails
pipeline:
  build:
    commands:
      - "go get ./..."
      - "go test"
      - "go build"
    image: "golang:latest"
  publish:
    image: plugins/docker
    registry: quay.io
    username: drone2
    token: ${qtoqtoken}
    repo: drone2/awsdetails
    tags:
      - 1
      - 1.1
      - latest